# Generated by Django 5.0.3 on 2024-04-24 05:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_likes_alter_comment_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_1', to=settings.AUTH_USER_MODEL),
        ),
    ]
